### ISSUE TITLE
ClassifierResults only returns one value: Car

### ISSUE THREAD

**Issue by JohannesSteimel7P** [sobri909/ArcKit#80]
Hi Matt,
I'm currently trying out your LocoKit Demo App. Yesterday I generated an API key and startet tracking but the results in the ClassifierView contained only one ClassifierResultItem (car) instead of multiple.

**ClassifierResults(results: [LocoKit.ClassifierResultItem(name: LocoKit.ActivityTypeName.car, score: 0.0, modelAccuracyScore: Optional(0.965837))], $__lazy_storage_$_arrayIterator: nil, moreComing: false)**

At first I thought I did something wrong but then a took a small walk with the Arc App where it even counted my steps but still categorized it as "car". Am I missing something or is there currently an issue with the LocoKit API?

![IMG_DDC9116F8F27-1](https://user-images.githubusercontent.com/89850192/131811644-4617e00c-96fe-4bb7-8975-d4eab7abc336.jpeg)

**Comment by sobri909** [comment]
Hmm. It's a long time since I've used the Demo App, so I'm not sure if it's using up to date code. I recommend trying the Arc Mini project instead, as a more comprehensive demo app, with fully up to date code. 

https://github.com/sobri909/ArcMini

See how you get on with that one.

**Comment by JohannesSteimel7P** [comment]
Thanks for the quick response. For now I'm going to use Apples CMMotionActivityManager but maybe I'll have a look at ArcMini later on.
