### ISSUE TITLE
Machine Learning Classifiers

### ISSUE THREAD

**Issue by jayeshdesai4520** [sobri909/ArcKit#88]
Hey Matt,
Thank you for providing this library,

I have few questions about the ML Classifier,

I think you are using 2 classifiers,
One of them are detecting walk, cycle, etc and vehicle
And the other one goes deep into vehicle and gives activity types like car, bus, train etc

so my questions are:

1) can you tell us about what dataset you have used to train the ml models?
2) what types of model you have used for training? Is it random forest? Or some other?
3) is it possible to open source the ml code so we can learn more about it, specifically model code and feature engineering etc!
4) and I am curious to know how it is working? Like what are the features you have used to feed the models? And also when the app is terminated/suspended, I guess you are getting gps info and other sensors info at uneven interval so how do you use them for ml model classifier?

Looking forward to your reply!

**Comment by sobri909** [comment]
Hi @jayeshdesai4520!

I recommend checking out the [core-ml](https://github.com/sobri909/LocoKit/tree/core-ml) branch, which is the most recent and active. I've replaced the old handmade classifiers with ones built with Core ML. They're more accurate and more efficient. 

> can you tell us about what dataset you have used to train the ml models?

The server provided models used with the old system are built from anonymised activity data from users of Arc App. Though those server provided models will be going away some time later this year, so it wouldn't be wise to build anything new that makes use of them. 

> what types of model you have used for training? Is it random forest? Or some other?

The old system was Naive Bayes, and the new Core ML based system uses [MLBoostedTreeClassifiers](https://developer.apple.com/documentation/createml/mlboostedtreeclassifier). 

> is it possible to open source the ml code so we can learn more about it, specifically model code and feature engineering etc!

Both the old and new systems are all open sourced, available in this repo! Have a look in the `Timelines/ActivityTypes` folder.

> and I am curious to know how it is working? Like what are the features you have used to feed the models?

You can see what model features the Core ML based models are using [here](https://github.com/sobri909/LocoKit/blob/core-ml/LocoKit/Timelines/ActivityTypes/Core%20ML/CoreMLFeatureProvider.swift). The old Naive Bayes ones use basically the same set of features too.

> And also when the app is terminated/suspended, I guess you are getting gps info and other sensors info at uneven interval so how do you use them for ml model classifier?

The short answer is I don't. If the app is terminated everything stops, and there's a gap in the data until the app is relaunched.

It's really important to educate users not to swipe apps closed, both in general (it worsens their phone's battery life, ie the complete opposite of what they think they're achieving), makes it harder for apps to do their jobs, and impossible for some apps to do their jobs (eg long running location data based apps). 

You can also put in a bunch of fallbacks and safety nets to try to get the app automatically relaunched, if it is terminated. In best case scenarios these might get the app relaunched within 15 minutes or so, but on average you're looking at either hours until relaunch or no automatic relaunch at all. So yeah, educate users not to swipe apps closed.
